name:                submerge
version:             0.1.0.0
github:              "githubuser/submerge"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/submerge#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- case-insensitive
- containers
- directory
- exceptions
- feed
- filepath
- http-client
- http-conduit
- http-types
- monad-logger
- rio
- text
- yaml
- xml-conduit
- xml-types

library:
  source-dirs: src
  default-extensions:
    - DeriveAnyClass
    - DeriveGeneric
    - LambdaCase
    - NoImplicitPrelude
    - OverloadedStrings
    - RankNTypes
    - RecordWildCards
    - StandaloneDeriving
    - TemplateHaskell

executables:
  submerge-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - submerge

tests:
  submerge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - submerge
